# Generated by Django 5.2 on 2025-08-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(choices=[('cardio', 'НИИ Кардиологии'), ('oncology', 'НИИ Онкологии'), ('tumen', 'Тюменский кардиологический научный центр'), ('pz', 'НИИ Психического здоровья'), ('medgenetics', 'НИИ Медицинского генетики'), ('pharma', 'НИИ Фармакологии и регенеративной медицины'), ('head', 'Аппарат управления ТНИМЦ')], default=None, max_length=50),
        ),
    ]
