# Generated by Django 5.2 on 2025-04-10 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='answer_text',
            new_name='answer_data',
        ),
        migrations.CreateModel(
            name='SelectedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=True)),
                ('answer_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.answeroption')),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_answers', to='courses.useranswer')),
            ],
            options={
                'unique_together': {('user_answer', 'answer_option')},
            },
        ),
    ]
