# Generated by Django 5.2 on 2025-05-29 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_answer_text_useranswer_answer_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='test',
            name='max_score',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'question', 'attempt_number')},
        ),
    ]
