# Generated by Django 5.2 on 2025-08-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_useranswer_attempt_number_alter_test_max_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./media/'),
        ),
    ]
