# Generated by Django 5.2 on 2025-08-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_questionimage_alter_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.DeleteModel(
            name='QuestionImage',
        ),
    ]
